In [41]:
import numpy as np
import pandas as pd
import re
import string
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df.shape

(50000, 2)

## Lower Casing

In [4]:
df['review'] = df['review'].str.lower()

In [5]:
df.sample(5)

                                                  review sentiment
26129  i saw this video at a friends house, and it wa...  negative
26027  i always enjoy watching this cartoon, with syl...  positive
48820  et's obsession with dannielynn smith is despic...  negative
14819  i haven't actually seen a lot of movies with h...  positive
49718  there is a lot of crap coming out of hollywood...  positive

## Removing HTML Tags

In [6]:
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [7]:
text = "<html><body><p> Movie 1</p><p> Actor - Aamir Khan</p><p> Click here to <a href='http://google.com'>download</a></p></body></html>"

remove_html_tags(text)

' Movie 1 Actor - Aamir Khan Click here to download'

In [8]:
df['review'] = df['review'].apply(remove_html_tags)

In [9]:
df['review'].sample(5)

17312    i am a music lover and was excited to see this...
20411    i completely agree with the other comment some...
29309    izzard was both hysterical and insightful in h...
45758    this film is a third rate attempt at a compell...
30809    i remember this movie from when i was 12, it w...
Name: review, dtype: object

## Removing URLs

In [10]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [11]:
text1 = 'Check out this notebook https://www.kaggle.com/campusx/notebook8223fc1abb'
text2 = 'Check out my notebook http://www.kaggle.com/campusx/notebook8223fc1abb'
text3 = 'Google search here www.google.com'
text4 = 'For notebook click https://www.kaggle.com/campusx/notebook8223fc1abb to search check www.google.com'

In [12]:
print(remove_url(text1))
print(remove_url(text2))

Check out this notebook
Check out my notebook

In [13]:
print(remove_url(text3))
print(remove_url(text4))

Google search here
For notebook click  to search check

## Removing Punctuations

In [14]:
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [15]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [16]:
text = 'string. With. Punctuation?'

remove_punc(text)  # Slow method

'string With Punctuation'

In [17]:
def remove_punc_new(text):
    return text.translate(str.maketrans('', '', exclude))

In [18]:
text = 's@tring.# Wit%h. Pun?ctuati*on?'

remove_punc_new(text)  # Fast method

'string With Punctuation'

## Chat word treatment

In [19]:
chat_words = {
    'IMHO' : 'In My Humble Opinion',
    'LOL' : 'Laughing Out Loud',
    'BRB' : 'Be Right Back',
    'IDK' : 'I Don\'t Know',
    'TBH' : 'To Be Honest',
    'BTW':'By The Way',
    'FYI':'For Your Information'
}

In [20]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
            
    return " ".join(new_text)

In [21]:
chat_conversion('IMHO he is the best')

'In My Humble Opinion he is the best'

In [22]:
chat_conversion('FYI delhi is the capital of india')

'For Your Information delhi is the capital of india'

## Spelling Correction

In [23]:
from textblob import TextBlob

In [24]:
incorrect_text = 'ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner.'

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner.'

## Removing Stopwords

In [25]:
from nltk.corpus import stopwords

In [26]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [27]:
def remove_stopwords(text):
    new_text = []
    
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    
    return " ".join(x)

In [28]:
remove_stopwords('probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times')

'probably  all-time favorite movie,  story  selflessness, sacrifice  dedication   noble cause,    preachy  boring.   never gets old, despite   seen   15   times'

In [29]:
# df['review'].apply(remove_stopwords)

# df['review'].sample(5)

## Handling Emojis

In [30]:
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    
    return emoji_pattern.sub(r'', text)

In [31]:
remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

In [32]:
remove_emoji("Lmao 😂😂")

'Lmao '

In [33]:
import emoji

print(emoji.demojize('Python is 🔥'))

Python is :fire:

In [34]:
print(emoji.demojize('Loved the movie. It was 😘'))

Loved the movie. It was :face_blowing_a_kiss:

## Tokenization

### 1. Using split function

In [35]:
# Word tokenization
sent1 = 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [37]:
# Sentence tokenization
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [38]:
# Problems with split function
sent3 = 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [39]:
sent4 = 'Where do think I should go? I have 3 day holiday'
sent4.split('.')

['Where do think I should go? I have 3 day holiday']

### 2. Using Regular Expression

In [ ]:
sent3 = 'I am going to delhi!'
tokens = re.findall("[\w']+", sent3)  # Word tokenization
tokens

['I', 'am', 'going', 'to', 'delhi']

In [ ]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry? 
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sentences = re.compile('[.!?] ').split(text)  # # Sentence tokenization
sentences

['Lorem Ipsum is simply dummy text of the printing and typesetting industry',
 "\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s, \nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

### 3. Using NLTK

In [44]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [45]:
sent1 = 'I am going to visit delhi!'

word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [46]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry? 
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, \nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [48]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [49]:
print(word_tokenize(sent6))
print(word_tokenize(sent7))

['We', "'re", 'here', 'to', 'help', '!', 'mail', 'us', 'at', 'nks', '@', 'gmail.com']
['A', '5km', 'ride', 'cost', '$', '10.50']

### 4. Using Spacy

In [52]:
import spacy

In [53]:
nlp = spacy.load('en_core_web_sm')

In [55]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [58]:
for token in doc1:
    print(token)

I
have
a
Ph
.
D
in
A.I

In [59]:
for token in doc2:
    print(token)

We
're
here
to
help
!
mail
us
at
nks@gmail.com

In [60]:
for token in doc3:
    print(token)

A
5
km
ride
cost
$
10.50

In [61]:
for token in doc4:
    print(token)

I
am
going
to
visit
delhi
!

## Stemming

In [62]:
from nltk.stem.porter import PorterStemmer

In [63]:
ps = PorterStemmer()

def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [64]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [66]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

## Lemmatization

In [75]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\gupta\AppData\Roaming\nltk_data...

True

In [76]:
from nltk.stem import WordNetLemmatizer

In [ ]:
wl = WordNetLemmatizer()

In [78]:
sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"

sentence_words = nltk.word_tokenize(sentence)

for word in sentence_words:
    
    if word in punctuations:
        sentence_words.remove(word)

In [79]:
sentence_words

['He',
 'was',
 'running',
 'and',
 'eating',
 'at',
 'same',
 'time',
 'He',
 'has',
 'bad',
 'habit',
 'of',
 'swimming',
 'after',
 'playing',
 'long',
 'hours',
 'in',
 'the',
 'Sun']

In [ ]:
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wl.lemmatize(word,pos='v')))

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun